name: Daily Voucher Scrape

on:
  schedule:
    - cron: "0 8 * * *" # Run daily at 8am UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install Playwright browsers
        run: bunx playwright install chromium --with-deps

      - name: Run scraper
        run: bun run scrape
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Commit changes to DB
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add packages/db/data
          git commit -m "Update voucher database" || echo "No changes to commit"
          git push
